### ISSUE TITLE
Accessing http://www.onruby.dev:5000/ makes unicorn die in development

### ISSUE THREAD

**Issue by kikito** [phoet/on_ruby#156] opened 2015-01-13 22:54 UTC
I tried accessing http://www.onruby.dev:5000/ from my machine (new folder, cloning directly from phoet/on_ruby to discards problems with local changes) and the unicorn worker kept dying.

Here's what the console shows:

```
I, [2015-01-13T23:50:37.960770 #4449]  INFO -- : listening on addr=0.0.0.0:5000 fd=11
I, [2015-01-13T23:50:39.013059 #4449]  INFO -- : master process ready
I, [2015-01-13T23:50:39.022411 #4463]  INFO -- : worker=0 ready
E, [2015-01-13T23:50:55.026210 #4449] ERROR -- : worker=0 PID:4463 timeout (6s > 5s), killing
E, [2015-01-13T23:50:55.039496 #4449] ERROR -- : reaped #<Process::Status: pid 4463 SIGKILL (signal 9)> worker=0
I, [2015-01-13T23:50:56.058441 #4480]  INFO -- : worker=0 ready
D, [2015-01-13T23:51:00.050829 #4449] DEBUG -- : waiting 3.5s after suspend/hibernation
E, [2015-01-13T23:51:03.555214 #4449] ERROR -- : worker=0 PID:4480 timeout (7s > 5s), killing
E, [2015-01-13T23:51:03.573650 #4449] ERROR -- : reaped #<Process::Status: pid 4480 SIGKILL (signal 9)> worker=0
I, [2015-01-13T23:51:04.595964 #4495]  INFO -- : worker=0 ready
D, [2015-01-13T23:51:08.588831 #4449] DEBUG -- : waiting 3.5s after suspend/hibernation
```

**Comment by phoet** [comment] 2015-01-14 06:21
this issue was introduced with ruby 2.2.0 and i've seen it myself. can you try running `script/server` and check the logs if there is anything related to assets?

**Comment by phoet** [comment] 2015-01-14 06:24
if you can't get it working for yourself, feel free to downgrade to 2.1

**Comment by kikito** [comment] 2015-01-14 19:11
> can you try running script/server and check the logs if there is anything related to assets?

`log/development.log` shows the following:

    <installing gems and migrating db>

    www.onruby.dev] Started GET "/" for 127.0.0.1 at 2015-01-13 23:49:03 +0100
    [www.onruby.dev] Processing by LabelsController#index as HTML
    [www.onruby.dev]   Rendered labels/index.slim within layouts/labels (47.2ms)
    [www.onruby.dev]   Rendered shared/_meta.slim (6.8ms)
    Disconnected from ActiveRecord
    Connected to ActiveRecord
    [www.onruby.dev]
    [www.onruby.dev]
    [www.onruby.dev] Started GET "/" for 127.0.0.1 at 2015-01-13 23:49:09 +0100
    [www.onruby.dev]   ActiveRecord::SchemaMigration Load (0.8ms)  SELECT "schema_migrations".* FROM "schema_migrations"
    [www.onruby.dev] Processing by LabelsController#index as HTML
    [www.onruby.dev]   Rendered labels/index.slim within layouts/labels (535.5ms)
    [www.onruby.dev]   Rendered shared/_meta.slim (5.7ms)

The last 10 lines (starting with `Disconnected ...`)  are repeated several times. That's all I see in the logs.

> if you can't get it working for yourself, feel free to downgrade to 2.1

Will try that, thanks.

**Comment by phoet** [comment] 2015-01-15 11:16
i havn't had the chance to really dig into it as it just happens once a while on my machine (only one of them) but there are some incompatibles with ruby 2.2.0 that have subtle side-effects like this one: https://github.com/Compass/compass/pull/1903

**Comment by phoet** [comment] 2015-02-18 20:26
merged passenger5 into master, so this should not be an issue any longer. unfortunately it looks like there are some performance regressions, so i'm considdering switching to puma as it's been promoted to the default heroku server.

**Closed by phoet** 2015-02-18 20:26 UTC
